server:
  applicationConnectors:
  - type: http
    port: 5000
    httpCompliance: RFC7230_LEGACY
  adminConnectors:
  - type: http
    port: 5001

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://${POSTGRES_HOST:-airflow-metadata}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-marquez}
  user: ${POSTGRES_USER:-airflow}
  password: ${POSTGRES_PASSWORD:-airflow}

migrateOnStartup: true

graphql:
  enabled: true

logging:
  level: INFO
  appenders:
    - type: console

search:
  enabled: false
