# =====================================================================
# SPARK DEFAULT CONFIGURATION
# =====================================================================
# File này chứa các cấu hình mặc định cho tất cả Spark Jobs chạy trong container.
# Giúp loại bỏ việc phải truyền --packages hoặc cấu hình cứng trong code Python.

# Các Maven Packages mặc định cần tải (Kafka, Iceberg, Postgres JDBC, AWS S3)
spark.jars.packages   org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3,org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0,org.postgresql:postgresql:42.6.0,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
